### ISSUE TITLE
PUT deletes the PNG's from nodpi/xxxhdpi

### ISSUE THREAD

**Issue by PrinceAbid** [afollestad/polar-dashboard-upgrade-tool#4]
hello,
the PUT was successful, but with one problem, it might be a bug or so.. i came across this problem, the png icons from my xxhdpi/nodpi where deleted or vanished, please have a look at this problem.. thank you, you rock...

**Comment by PrinceAbid** [comment]
oh wait, it delets all icons we have replaced in all folders..

**Comment by afollestad** [comment]
Are you sure they get deleted from `drawable-nodpi`? That folder is skipped.

---

The other folders do get overwritten, yes. That's intended.

**Comment by afollestad** [comment]
Actually I know `drawable-nodpi` doesn't get overwritten, because I've run PUT with Gaufrer many times.
